---
title: "RWorksheet_Española#2"
author: "Jacklord Española"
date: "`r Sys.Date()`"
output: pdf_document
---

#Worksheet-2 in R
```{r, include=TRUE}
#1.	Create a vector using : #operator

#a.	
 operator <- c(-5:5)
  operator
  
#b.
  x <- seq(1:7)
  x

```

```{r, incude=TRUE}
#2.	* Create a vector using #seq() function
#a.
vector <- seq(1, 3, by=0.2)
vector
```

```{r, include=TRUE}
#3.A factory has a census of #its workers. There are 50 #workers in total. The #following list  shows their #ages 34, 28, 22, 36, 27, 18, #52, 39, 42, 29, 35, 31, 27, #22, 37, 34, 19, 20, 57, 49, #50, 37, 46, 25, 17, 37, 43, #53, 41, 51, 35, 24,33, 41, 53, #40, 18, 44, 38, 41, 48, 27, #39, 19, 30, 61, 54, 58, 26, #18.
workers_Age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,

             22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,   24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
             18)
workers_Age
#a.
workers_Age[3]
#b.
workers_Age[2]
workers_Age[4]
#c
workers_Age[2:49]
```

```{r, include=TRUE}
#4.
#a.
x <- c("first"=3, "second"=0, "third"=9)
x
  x[c("first", "third")]
```

```{r, include=TRUE}
#5. Create a sequence x from #-3:2.
x <- c(-3:2)
x
#a.
x[2] <- 0
x

```

```{r, include=TRUE}
#6. *The following data shows #the diesel fuel purchased by #Mr. Cruz.
#a.
diesel <- data.frame(Month = c("Jan", "Feb", "March", "April", "May", "June"),
  Price = c("52.50", "57.25", "60.00", "65.00", "74.25", "54.00"),
  Purchase = c("25", "30", "40", "50", "10", "45")
)
diesel

#b
price <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)  
price
 quantity <- c(25, 30, 40, 50, 10, 45) 
 quantity
 weighted.mean(price, quantity)
```

```{r, include=TRUE}
#7.  R has actually lots of #built-in datasets. For #example, the rivers data #“gives the lengths (in miles) #of 141 “major” rivers in North #America, as compiled by the US #Geological Survey”.
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
data
```

```{r, include=TRUE}
#8. The table below gives the #25 most powerful celebrities #and their annual pay as ranked #by the editions of Forbes #magazine and as listed on the #Forbes.com website.

#a
PowerRanking <- 1:25
CelebrityName <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", 
                   "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40,
         233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

Data_Ranking <- data.frame(PowerRanking, CelebrityName, Pay)
Data_Ranking

#b
PowerRanking [19] <- 15
PowerRanking
Pay [19] <- 90
Pay

Magazine_Ranking <- data.frame(PowerRanking, CelebrityName, Pay)
Magazine_Ranking
```

