---
title: 'INDIVIDUAL PROJECT #1'
author: "Jacklord Espanola"
date: "2022-12-02"
output: html_document
---

```{r, include=TRUE}

#Packages that will be needed 
library(twitteR)
library(tm)
library(dplyr)
library(plotly)
library(ggplot2)
library(RColorBrewer)
library(tidytext)
library(stringr)
library(tidyr)
library(magrittr)
library(corpus)
library(rtweet)
library(slam)
library(wordcloud)
library(wordcloud2)

```


```{r, include=TRUE}
#1. Extract from twitter using your developer's credentials. Choose any keyword you want. 

#place your own token key and secret
# set the credentials
CONSUMER_SECRET <- "8LvRHk6qo04uwR5MD3LiBFQjKkntdScxp965Ig8cUGDHfrYskw"
CONSUMER_KEY <- "i9BRjoSEXukdBdAVhQi6tistg"
ACCESS_SECRET <- "HyHUdA1S9nVoncvWwokPAwNPf6isQOTStXj7exKE0vYX9"
ACCESS_TOKEN <- "1595426639126880257-eqts7cMokyHWn8A59Wj3B9pJzzQEmO"
```

```{r, include=TRUE}
# connect to twitter app
setup_twitter_oauth(consumer_key = CONSUMER_KEY,
                    consumer_secret = CONSUMER_SECRET,
                    access_token = ACCESS_TOKEN,
                    access_secret = ACCESS_SECRET)


```


```{r, include=TRUE}
#2. Get 10000 observations "excluding retweets.

tweeeToday <- searchTwitter("SB19 -filter:retweets", 
                            n = 10000,
                            lang = 'en',
                            since = "2022-11-21",
                            until = "2022-11-30",
                            retryOnRateLimit = 120)
tweeeToday

```

```{r, include=TRUE}
#Converting data into dataframe

tweetS <- twListToDF(tweeeToday)
tweetS
```

```{r, include=TRUE}
#Saving the data into a file
save("tweetS", file = "tweetS.Rdata")
load("tweetS.Rdata")
```


```{r, include=TRUE}
#3. Plot the time series from the date created. with legends.
library(rtweet)
sbData <- ts_plot(tweetS, "hours") +
  labs(x = NULL, y = NULL,
       title = "Frequency of tweets with a #SB19 hashtag",
       subtitle = paste0(format(min(tweetS$created), "%d %B %Y"), " to ", 
                         format(max(tweetS$created),"%d %B %Y")),
       caption = "Data collected from Twitter's REST API via twitteR") + 
  theme_minimal()

ggplotly(sbData)
```


```{r, include=TRUE}
#4. Plot a graph (any graph you want)  based on the type of device - found in Source
#- that the user use. Include the legends.
encodeSource <- function(x) {
  if(grepl(">Twitter for iPhone</a>", x)){
    "iphone"
  }else if(grepl(">Twitter for iPad</a>", x)){
    "ipad"
  }else if(grepl(">Twitter for Android</a>", x)){
    "android"
  } else if(grepl(">Twitter Web Client</a>", x)){
    "Web"
  } else if(grepl(">Twitter for Windows Phone</a>", x)){
    "windows phone"
  }else if(grepl(">dlvr.it</a>", x)){
    "dlvr.it"
  }else if(grepl(">IFTTT</a>", x)){
    "ifttt"
  }else if(grepl(">Facebook</a>", x)){  #This looks unreliable...
    "facebook"
  }else {
    "others"
  }
}
```

```{r, include=TRUE}
tweetS$tweetSource = sapply (tweetS$statusSource, 
                             encodeSource)
tweet_appSource <- tweetS %>% 
  select(tweetSource) %>%
  group_by(tweetSource) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 
Source_subset <- subset(tweet_appSource,count >10)

dataDF <- data.frame(
  category = tweet_appSource$tweetSource,
  count = tweet_appSource$count
)
dataDF$fraction = dataDF$count / sum(dataDF$count)
dataDF$percentage = dataDF$count / sum(dataDF$count) * 100
dataDF$ymax = cumsum(dataDF$fraction)
dataDF$ymin = c(0, head(dataDF$ymax, n=-1))
dataDF$roundP = round(dataDF$percentage, digits = 2)
tweetS$tweetSource = sapply(tweetS$statusSource, 
                              encodeSource)
```

```{r, include=TRUE}
#Without Values
ggplot(dataDF,aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, 
                  fill=category)) +
  geom_rect() +
  coord_polar(theta="y") + 
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "right")
```

```{r, include=TRUE}
#With Values
Source <- paste(dataDF$category, dataDF$roundP, "%")

ggplot(dataDF, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Source)) +
  geom_rect() +
  coord_polar(theta="y") + # Try to remove that to understand how the chart is built initially
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "right")
```


```{r, include=TRUE}
#5. Create a wordcloud from the screenName
#Using wordcloud() package but using a shape pentagon 
tweet_appScreen <- tweetS %>%
  select(screenName) %>%
  group_by(screenName) %>%
  summarize(count=n()) %>%
  arrange(desc(count)) 


#convert to Corpus
namesCorpus <- Corpus(VectorSource(tweetS$screenName))

#Running the code using the wordcloud()
wordcloud2(data=tweet_appScreen, 
           size=0.8, 
           color='random-light',
           shape = 'pentagon')
```
